name: uwu_stack
services:
  uwu_server_devel:
    build:
      dockerfile: uwu_server.Dockerfile
      target: devel
    env_file:
      - path: ./environment/server/.env.example
        required: true
      - path: ./environment/server/.env
        required: false
    depends_on:
      directory:
        condition: service_healthy
    volumes:
      - "php_socket:/var/run"
      - "./server:/var/www/uwu"
      - "./persist/server/var/uwu:/var/uwu"
    profiles: ["devel"]

  uwu_server_prod:
    build:
      dockerfile: uwu_server.Dockerfile
      target: prod
    env_file:
      - path: ./environment/server/.env.example
        required: true
      - path: ./environment/server/.env
        required: false
    depends_on:
      directory:
        condition: service_healthy
    volumes:
      - "php_socket:/var/run"
      - "web_data:/var/www/uwu"
      - "./persist/server/var/uwu:/var/uwu"
    profiles: ["prod"]

  uwu_server_test:
    build:
      dockerfile: uwu_server.Dockerfile
      target: test
    env_file:
      - path: ./environment/server/.env.example
        required: true
      - path: ./environment/server/.env
        required: false
    depends_on:
      directory:
        condition: service_healthy
    volumes:
      - "php_socket:/var/run"
      - "web_data:/var/www/uwu"
    profiles: ["test"]

  web_devel:
    image: nginx:latest
    healthcheck:
      test: service nginx status || exit 1
    ports:
      - "8018:80"
    depends_on:
      uwu_server_devel:
        condition: service_healthy
    volumes:
      - "php_socket:/var/run"
      - "./server:/var/www/uwu"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    profiles: ["devel"]

  web_prod:
    image: nginx:latest
    healthcheck:
      test: service nginx status || exit 1
    ports:
      - "8018:80"
    depends_on:
      uwu_server_prod:
        condition: service_healthy
    volumes:
      - "php_socket:/var/run"
      - "web_data:/var/www/uwu"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    profiles: ["prod"]

  directory:
    hostname: "dc1"
    image: smblds/smblds:latest
    env_file:
      - path: ./environment/smblds/.env.example
        required: true
      - path: ./environment/smblds/.env
        required: false
    ports:
      - "636:636"
    volumes:
      - "./config/smblds/entrypoint.d:/entrypoint.d"
      - "./persist/smblds/var/lib/samba:/var/lib/samba"
      - "./persist/smblds/etc/samba:/etc/samba"
      - "./persist/smblds/var/log/samba:/var/log/samba"
      - "./persist/smblds/var/cache/samba:/var/cache/samba"
    profiles: ["devel", "test", "prod"]

volumes:
  php_socket:
  web_data:

networks:
  backend:
    driver: bridge