name: uwu_stack

services:
  server:
    build:
      dockerfile: ./uwu_server.Dockerfile
      target: uwu_server
    env_file:
      - path: ./environment/server/.env.example
        required: true
      - path: ./environment/server/.env
        required: false
    depends_on:
      directory:
        condition: service_healthy
    volumes:
      - type: volume
        source: uwu_config
        target: /etc/uwu
    ports:
      - "8018:80"
    develop:
      watch:
        - path: ./server
          action: sync
          target: /var/www/uwu
          ignore:
            - node_modules/
            - var/
            - vendor/

  directory:
    hostname: "dc1"
    image: smblds/smblds:latest
    env_file:
      - path: ./environment/smblds/.env.example
        required: true
      - path: ./environment/smblds/.env
        required: false
    ports:
      - "636:636"
    volumes:
      - type: bind
        source: ./sh/directory_provision.sh
        target: /entrypoint.d/provision.sh
        read_only: true
      - type: volume
        source: smb_var_lib
        target: /var/lib/samba
      - type: volume
        source: smb_var_log
        target: /var/log/samba
      - type: volume
        source: smb_var_cache
        target: /var/cache/samba
      - type: volume
        source: smb_etc
        target: /etc/samba

volumes:
  uwu_config:
  smb_var_lib:
  smb_var_log:
  smb_var_cache:
  smb_etc:

networks:
  backend:
    driver: bridge