services:
  php:
    build: ./server/
    env_file: ".env.symfony.prod"
    volumes:
      - "phpsocket:/var/run"
      - "webdata:/var/www/project"
      - "./config/project.fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"

  web:
    image: nginx:latest
    ports:
     - "8018:80"
    volumes:
      - "phpsocket:/var/run"
      - "webdata:/var/www/project"
      - "./config/project.nginx.conf:/etc/nginx/conf.d/default.conf"

volumes:
  phpsocket:
  webdata: