name: uwu_stack

services:
  server: &server
    build:
      dockerfile: ./uwu_server.Dockerfile
      target: prod
    env_file:
      - path: ./environment/server/.env.example
        required: true
      - path: ./environment/server/.env
        required: false
    depends_on:
      directory:
        condition: service_healthy
    volumes:
      - type: volume
        source: php_socket
        target: /var/run/uwu
      - type: volume
        source: uwu_config
        target: /var/uwu
      - type: volume
        source: php_public
        target: /var/www/uwu/public
    develop:
      watch:
        - path: ./server
          action: sync
          target: /var/www/uwu
          ignore:
            - node_modules/
            - var/
            - vendor/
    profiles: ["devel", "prod"]

  server_ci:
    <<: *server
    build:
      dockerfile: ./uwu_server.Dockerfile
      target: test
    volumes: []
    profiles: ["test"]

  nginx:
    image: nginx:latest
    healthcheck:
      test: service nginx status || exit 1
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "8018:80"
    volumes:
      - type: volume
        source: php_socket
        target: /var/run/uwu
      - type: volume
        source: php_public
        target: /var/www/uwu/public
      - type: bind
        source: ./config/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    profiles: ["prod", "devel"]

  directory:
    hostname: "dc1"
    image: smblds/smblds:latest
    env_file:
      - path: ./environment/smblds/.env.example
        required: true
      - path: ./environment/smblds/.env
        required: false
    ports:
      - "636:636"
    volumes:
      - type: bind
        source: ./config/smblds/entrypoint.d
        target: /entrypoint.d
        read_only: true
      - type: volume
        source: smb_var_lib
        target: /var/lib/samba
      - type: volume
        source: smb_var_log
        target: /var/log/samba
      - type: volume
        source: smb_var_cache
        target: /var/cache/samba
      - type: volume
        source: smb_etc
        target: /etc/samba
    profiles: ["devel", "test", "prod"]

volumes:
  php_socket:
  php_public:
  uwu_config:
  smb_var_lib:
  smb_var_log:
  smb_var_cache:
  smb_etc:

networks:
  backend:
    driver: bridge