name: infra
services:
  php:
    build:
      dockerfile: compose/build/server.Dockerfile
      context: ../
    env_file: "../environment/server/.env"
    depends_on:
      - directory
      - db
    volumes:
      - "php_socket:/var/run"
      - "web_data:/var/www/project"
      - "../config/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"
      - "../secrets/var/oauth:/var/oauth"

  web:
    image: nginx:latest
    healthcheck:
      test: service nginx status || exit 1
    ports:
     - "8018:80"
    depends_on:
      - php
    volumes:
      - "php_socket:/var/run"
      - "web_data:/var/www/project"
      - "../config/default.conf:/etc/nginx/conf.d/default.conf"

  directory:
    hostname: "dc1"
    image: smblds/smblds:latest
    env_file: "../environment/smblds/.env"
    ports:
      - "636:636"
    volumes:
      - "../persist/entrypoint.d:/entrypoint.d"
      - "../persist/var/lib/samba:/var/lib/samba"
      - "../persist/etc/samba:/etc/samba"
      - "../persist/var/log/samba:/var/log/samba"
      - "../persist/var/cache/samba:/var/cache/samba"

volumes:
  php_socket:
  web_data:

networks:
  backend:
    driver: bridge