name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run PHPUnit
      run: docker compose --profile test up --abort-on-container-exit --menu=false
    - name: Parse Commit SHA to Container Tag
      run: echo "CONTAINER_TAG=main_$(git log --pretty=format:'%h' -n 1)" >> $GITHUB_ENV
    - name: Build & Export Production Container
      run: | 
        docker build \
          -f uwu_server.Dockerfile \
          --target prod \
          -t ghcr.io/jmelancon/uwu_server:${{ env.CONTAINER_TAG }} \
          -t ghcr.io/jmelancon/uwu_server:latest \
          .
        docker save ghcr.io/jmelancon/uwu_server:${{ env.CONTAINER_TAG }} | gzip > ${{ env.CONTAINER_TAG }}.tar.gz
    - name: Log In to Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Publish Image
      run: docker push ghcr.io/jmelancon/uwu_server:${{ env.CONTAINER_TAG }}
